[package]
name = "scheme-ish"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
thiserror = { version = "1.0" }

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "benchmarks"
harness = false
